export async function seed(knex) {
  await knex('users').del()
  await knex('users').insert([
    {
      id: 1,
      auth_id: 'auth0|64a92bd1e5c34d71b7f0a123',
      username: 'techwizard42',
      first_name: 'Aiden',
      last_name: 'Lowe',
      email: 'aiden.lowe@example.com',
      address_one: '12 Falcon Ridge',
      address_two: null,
      town_city: 'Hamilton',
      postcode: '3216',
      phone: '0213456789',
      image_url: 'user1.jpg',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 2,
      auth_id: 'auth0|98b12d49fe903ab4c5f781ee',
      username: 'silverbyte',
      first_name: 'Marisol',
      last_name: 'Quinn',
      email: 'marisol.quinn@example.com',
      address_one: '45 Oak Crescent',
      address_two: 'Unit 3',
      town_city: 'Wellington',
      postcode: '6021',
      phone: '0229876543',
      image_url: 'user2.jpg',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 3,
      auth_id: 'auth0|7f5c1ab3e0dcd920af334bb2',
      username: 'rigbuildernz',
      first_name: 'Tobias',
      last_name: 'Hartley',
      email: 'tobias.hartley@example.com',
      address_one: '9 Lakeview Road',
      address_two: null,
      town_city: 'Christchurch',
      postcode: '8041',
      phone: '0204567891',
      image_url: 'user3.jpg',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ])
}
